import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./ui/navigation/nav-bar";
import { barlow } from "./ui/fonts";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Footer from "./ui/footer/footer";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html className={cn("bg-[#1A1A1A]", "font-sans", geist.variable)}>
      <body className={`${barlow.className} antialiased`}>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
